name: Build and Export Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .

      - name: Save Docker image as tar
        run: |
          mkdir -p docker
          docker save flask-app:latest -o docker/flask-app.tar

      - name: Upload Docker tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker/flask-app.tar
